name: Terraform Apply

on:
  workflow_dispatch:

concurrency:
  group: terraform-apply
  cancel-in-progress: false

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: production  # You can configure GitHub approval for this env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -backend-config="path=terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
