- name: terraform-apply
  # You may pin to the exact commit or the version.
  # uses: dflook/terraform-apply@8903ce28e2bc45fb7e2d6d05b575c79ae5389923
  uses: dflook/terraform-apply@v1.29.1
  with:
    # Path to the terraform configuration
    path: # optional, default is .
    # Name of the terraform workspace
    workspace: # optional, default is default
    # List of backend config values to set, one per line
    backend_config: # optional, default is 
    # Path to a backend config file
    backend_config_file: # optional, default is 
    # Variable definitions
    variables: # optional
    # Comma separated list of vars to set, e.g. 'foo=bar'
    var: # optional, default is 
    # List of var file paths, one per line
    var_file: # optional, default is 
    # Limit the number of concurrent operations
    parallelism: # optional, default is 0
    # A friendly name for this plan
    label: # optional, default is 
    # Automatically approve and apply plan
    auto_approve: # optional, default is false
    # List of resources to target for the apply, one per line
    target: # optional, default is 
    # List of resources to replace if an update is required, one per line
    replace: # optional, default is 
          
