name: Terraform Plan

on:
  push:
    branches: [develop]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init -backend-config="path=terraform.tfstate"

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
